import { EventItem, ActivityItem } from './store'

const gradients = [
  'from-emerald-400 to-teal-600',
  'from-violet-400 to-purple-600',
  'from-amber-400 to-orange-600',
  'from-rose-400 to-pink-600',
  'from-cyan-400 to-sky-600',
  'from-lime-400 to-green-600',
  'from-fuchsia-400 to-purple-600',
  'from-teal-400 to-emerald-600',
  'from-orange-400 to-red-600',
  'from-indigo-400 to-violet-600',
]

export const sampleEvents: EventItem[] = [
  {
    id: '1',
    name: 'Tech Summit 2026',
    date: '2026-07-15',
    time: '09:00',
    venue: 'Grand Convention Center',
    attendees: 342,
    maxAttendees: 500,
    category: 'Conference',
    status: 'upcoming',
    description: 'The biggest technology conference of the year featuring keynotes from industry leaders.',
    ticketPrice: 299,
    imageGradient: gradients[0],
  },
  {
    id: '2',
    name: 'Design Workshop',
    date: '2026-06-20',
    time: '14:00',
    venue: 'Creative Hub Studio',
    attendees: 28,
    maxAttendees: 40,
    category: 'Workshop',
    status: 'ongoing',
    description: 'Hands-on workshop covering modern UI/UX design principles and Figma workflows.',
    ticketPrice: 79,
    imageGradient: gradients[1],
  },
  {
    id: '3',
    name: 'Summer Music Festival',
    date: '2026-08-05',
    time: '18:00',
    venue: 'Riverside Amphitheater',
    attendees: 1200,
    maxAttendees: 2000,
    category: 'Concert',
    status: 'upcoming',
    description: 'Three days of live music featuring top artists from around the world.',
    ticketPrice: 149,
    imageGradient: gradients[2],
  },
  {
    id: '4',
    name: 'Startup Meetup',
    date: '2026-06-12',
    time: '19:00',
    venue: 'Innovation Loft',
    attendees: 85,
    maxAttendees: 100,
    category: 'Meetup',
    status: 'ongoing',
    description: 'Networking event for startup founders and investors.',
    ticketPrice: 0,
    imageGradient: gradients[3],
  },
  {
    id: '5',
    name: 'AI & ML Conference',
    date: '2026-05-10',
    time: '10:00',
    venue: 'Tech Campus Hall',
    attendees: 450,
    maxAttendees: 450,
    category: 'Conference',
    status: 'completed',
    description: 'Deep dives into the latest AI and machine learning research and applications.',
    ticketPrice: 399,
    imageGradient: gradients[4],
  },
  {
    id: '6',
    name: 'Community Potluck',
    date: '2026-09-01',
    time: '12:00',
    venue: 'Central Park Pavilion',
    attendees: 56,
    maxAttendees: 150,
    category: 'Social',
    status: 'upcoming',
    description: 'A community gathering with food, games, and live entertainment for all ages.',
    ticketPrice: 0,
    imageGradient: gradients[5],
  },
  {
    id: '7',
    name: 'Photography Masterclass',
    date: '2026-04-22',
    time: '11:00',
    venue: 'Art Gallery Downtown',
    attendees: 20,
    maxAttendees: 25,
    category: 'Workshop',
    status: 'completed',
    description: 'Learn advanced photography techniques from award-winning photographers.',
    ticketPrice: 129,
    imageGradient: gradients[6],
  },
  {
    id: '8',
    name: 'Jazz Night',
    date: '2026-03-15',
    time: '20:00',
    venue: 'Blue Note Lounge',
    attendees: 0,
    maxAttendees: 80,
    category: 'Concert',
    status: 'cancelled',
    description: 'An evening of smooth jazz performances has been cancelled due to venue renovation.',
    ticketPrice: 45,
    imageGradient: gradients[7],
  },
  {
    id: '9',
    name: 'Developer Day',
    date: '2026-07-28',
    time: '09:30',
    venue: 'Grand Convention Center',
    attendees: 180,
    maxAttendees: 300,
    category: 'Conference',
    status: 'upcoming',
    description: 'A full day of talks, demos, and coding sessions for developers.',
    ticketPrice: 199,
    imageGradient: gradients[8],
  },
  {
    id: '10',
    name: 'Yoga & Wellness Retreat',
    date: '2026-08-20',
    time: '07:00',
    venue: 'Mountain View Resort',
    attendees: 30,
    maxAttendees: 50,
    category: 'Social',
    status: 'upcoming',
    description: 'A weekend retreat focused on mindfulness, yoga, and holistic wellness.',
    ticketPrice: 249,
    imageGradient: gradients[9],
  },
]

export const sampleActivities: ActivityItem[] = [
  {
    id: 'a1',
    user: 'Sarah Chen',
    avatar: 'SC',
    action: 'registered for',
    target: 'Tech Summit 2026',
    timestamp: '2026-06-05T00:00:00.000Z',
  },
  {
    id: 'a2',
    user: 'Alex Rivera',
    avatar: 'AR',
    action: 'added a new venue',
    target: 'Grand Hall',
    timestamp: '2026-06-04T22:00:00.000Z',
  },
  {
    id: 'a3',
    user: 'Maya Johnson',
    avatar: 'MJ',
    action: 'updated details for',
    target: 'Design Workshop',
    timestamp: '2026-06-04T20:00:00.000Z',
  },
  {
    id: 'a4',
    user: 'Tom Wilson',
    avatar: 'TW',
    action: 'cancelled',
    target: 'Jazz Night',
    timestamp: '2026-06-04T18:00:00.000Z',
  },
  {
    id: 'a5',
    user: 'Priya Patel',
    avatar: 'PP',
    action: 'registered for',
    target: 'Summer Music Festival',
    timestamp: '2026-06-04T16:00:00.000Z',
  },
  {
    id: 'a6',
    user: 'Jordan Lee',
    avatar: 'JL',
    action: 'created event',
    target: 'Yoga & Wellness Retreat',
    timestamp: '2026-06-04T12:00:00.000Z',
  },
  {
    id: 'a7',
    user: 'Emily Davis',
    avatar: 'ED',
    action: 'registered for',
    target: 'Developer Day',
    timestamp: '2026-06-03T00:00:00.000Z',
  },
  {
    id: 'a8',
    user: 'Marcus Brown',
    avatar: 'MB',
    action: 'exported report for',
    target: 'AI & ML Conference',
    timestamp: '2026-06-02T12:00:00.000Z',
  },
]

export const venues = [
  'Grand Convention Center',
  'Creative Hub Studio',
  'Riverside Amphitheater',
  'Innovation Loft',
  'Tech Campus Hall',
  'Central Park Pavilion',
  'Art Gallery Downtown',
  'Blue Note Lounge',
  'Mountain View Resort',
  'Grand Hall',
]
